### ISSUE TITLE
Upstream pytorch packages starting from 2.3.x require `llvm-openmp<16`, but this feedstock doesn't

### ISSUE THREAD

**Issue by anjos** [conda-forge/pytorch-cpu-feedstock#249]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

(I'm not sure this is relevant for this feedstock, but I thought I'd report it here for completeness.)

It seems the pinning of this package is outdated w.r.t. the upstream pytorch conda packages (from the `pytorch` channel).  Starting from pytorch 2.3.x, upstream conda packages have the following (very restrictive) runtime pin:

```yaml
- llvm-openmp <16  # [linux or arm64]
```

Reference: https://github.com/pytorch/builder/blob/main/conda/pytorch-nightly/meta.yaml#L49

The reason for this restriction seems to come from this (currently open) bug report: https://github.com/pytorch/pytorch/issues/99625

The restrictive pinning imposed by the upstream pytorch packages creates a nasty issue making it impossible to install newer versions of scikit-learn alongside pytorch packages (c.f. https://github.com/pytorch/builder/issues/1951, https://github.com/conda-forge/scikit-learn-feedstock/issues/271).

The question is: is that pin relevant here?  (i.e. is https://github.com/pytorch/pytorch/issues/99625 reproducible with this feedstock?). If so, this package may be required to also use that pin.  If not, then this is an indication that pin is possibly too restrictive and could potentially be relaxed from upstream.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by hmaarrfk** [comment]
I’m very sympathetic to these kinds of intergration issues but I’m having trouble following exactly what is happening. 

To my knowledge the channel combinations that are supported are as follows

* conda-forge and no other channnels
* defaults + PyTorch

I say this because otherwise we aren’t really able to reliably recreate the problematic test scenario. 

We typically allow more freedom in the OMP flavor installed. Do try to recreate. If you can I would be happy to help find the bug. But remember to only use one of the combinations listed above.

**Comment by anjos** [comment]
I guess we need first to check if https://github.com/pytorch/pytorch/issues/99625 is reproducible with the current builds on platforms `[linux or arm64]`.  Is it that issue reproducible with this feedstock?
