### ISSUE TITLE
Compatibility with upstream package names

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#74]
While I know that it isn't our primary goal to be compatible with all upstream packages, I think it would benefit conda-forge to be compatible with upstream packages.

This would benefit users of no-arch packages that depend on pytorch to be able to obtain pytorch. 

It would also allow us to test building procedures for windows packages while we are working toward windows packages.

Therefore, I guess I have two goals:

1. Allow users of noarch packages to enable both the conda-forge channel and the pytorch channel to install a package on windows.
2. Allow maintainers to test their recipes with windows + cuda while we work toward windows packages.

I see one major challenge:
The build string of packages on the pytorch channel is quite different than ours:

* `cuda11.2` vs `cuda112`
* `py3.8` vs `py38`
* cuda first in the build string. `py` first in the build string.

I'm not sure if it is worthwhile for us to try to find a solution, but it would be interesting if we could find one.

**Comment by jakirkham** [comment]
cc @benjaminrwilson @soumith @h-vetinari @rgommers (in case any of you have thoughts here)

cc @conda-forge/core (for awareness)

**Comment by rgommers** [comment]
Isn't there a specification of what this should look like somewhere? Is it uniform across conda-forge, or conda-forge + defaults?

**Comment by jakirkham** [comment]
We typically don’t use the `.`

**Comment by rgommers** [comment]
PyTorch will probably be okay to adapt, _if_ there's a compelling reason. It's unclear to me though that exact package name matching is a worthwhile effort, it should not have an impact on the 2 goals laid out here. For example, the CUDA version spelling is irrelevant, in both channels the correct package is chosen depending on the `cudatoolkit` version.

**Comment by jakirkham** [comment]
Yeah that seems reasonable.

The important thing is to make sure package names match and contain similar things.

There’s also discussion about new packages for CUDA Toolkit components in issue ( https://github.com/conda-forge/cudatoolkit-feedstock/issues/62 ), which would also be worth aligning on.

**Comment by h-vetinari** [comment]
> cc [...] @h-vetinari [...] (in case any of you have thoughts here)

Thanks @jakirkham. I agree with @hmaarrfk that the names should align, but they don't even do that yet within conda-forge (particularly the positioning of `cuda`/`cpu`, which is annoying because it's part of the selector syntax, and having to look up whether it's `pytorch =*=cuda*` or `pyarrow =*=*cuda` is not a good user experience).

IMO the ideal solution would be that `conda-build` provides reasonable defaults for build-strings of cuda-enabled packages (while keeping the option to override where necessary, of course). Every feedstock having to maintain their own definition is needlessly repetitive, brittle, and prone to the divergence we're now seeing.

**Comment by jaimergp** [comment]
Shouldn't `package=*=*cuda*` match both?
